export const education = [
  {
    degree: "Bachelor of Science in Engineering Physics",
    school: "Obafemi Awolowo University",
    duration: "2018 - 2023",
    details: [
      "Graduated with Upper Second Class Honors (2:1)",
      "Specialized in applied physics, polymers, and electronics",
      "Active member of the Engineering Students Association with participation in tech workshops and coding projects",
    ],
  },
  {
    degree: "Professional Certification in Frontend Development",
    school: "Udemy · Jonas Schmedtmann . Dave Gray",
    duration: "2021-2024",
    details: [
      "Completed a comprehensive curriculum covering HTML, CSS, JavaScript, and React",
      "Built 10+ responsive web applications",
      "Earned certifications in Responsive Web Design and JavaScript Algorithms",
    ],
  },
];

export const experiences = [
  {
    title: "Frontend AI Engineer",
    company: "Cartolinks Solutions Limited",
    duration: "September 2025 - present",
    details: [
      "Led frontend development for Soloa AI, building responsive AI-driven interfaces with Next.js",
      "Engineered AI features and integrations, focusing on real-time data and performance optimization",
      "Translated Figma designs into polished, interactive UIs",
      "Managed deployments and cloud resources to ensure seamless production delivery",
    ],
  },
  {
    title: "Frontend Engineer",
    company: "Vatebra Limited",
    duration: "June 2025 - present",
    details: [
      "Designed and deployed the EFCC Scholar Room Dashboard with role-based access for students, lecturers, admins, and section heads",
      "Built a multi-role trauma-informed app with portals for therapists, clients, and organizations",
      "Translated Figma mockups into responsive UIs and integrated real-time APIs",
      "Managed deployments and resources on Azure Cloud",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Petabyte Esports",
    duration: "June 2025 - December 2025",
    details: [
      "Leading frontend development of the ATIRC website, a platform to empower young African minds, featuring modules for jobs, research, incubation, and internship opportunities.",
      "Contributing to both the ATIRC and Petabyte Esports Gaming & Interactive Entertainment Platforms, focused on esports, social engagement, and youth-centered digital experiences.",
      "Built responsive UIs from Figma mockups and connected APIs to power real-time functionality",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Vynix Lab",
    duration: "June 2025 - September 2025",
    details: [
      "Contributed to OpenDust projects using Next.js, building responsive and interactive web applications",
      "Developed features and UI components for the StrakNet platform with a focus on performance and scalability",
      "Collaborated with the team via Git for version control and met deadlines through efficient project management",
    ],
  },

  {
    title: "Frontend Developer Intern",
    company: "HNG Internship",
    duration: "Jan 2025",
    details: [
      "Built scalable React + TypeScript apps using hooks, components, and Redux.",
      "Focused on clean, reusable code and maintainable architecture.",
      "Managed projects with Git and met deadlines through effective time management.",
    ],
  },
  {
    title: "Web Developer Intern",
    company: "CODSOFT",
    duration: "October 2024",
    details: [
      "Learned and applied the basics of HTML, CSS, and JavaScript to build interactive web pages.",
      "Worked on several projects, utilizing JavaScript for dynamic functionality and frontend logic.",
      "Developed and optimized frontend features, ensuring responsiveness and user-friendly interfaces using Tailwind CSS.",
    ],
  },
];

export const projects = [
  {
    id: 1,
    title: "Global Tech Ecommerce",
    description: `Global Tech Ecommerce is a responsive web app for exploring and buying tech gadgets. It features product filtering, cart/wishlist, Firebase authentication, state management with Redux Toolkit, and form validation using Zod.`,
    projectLink: "https://global-tech-ecommerce.vercel.app/",
    githubLink: "https://github.com/Royal-design/global-tech",
    imageLink: "/global_tech.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Zod",
      "React Hook Form",
      "Firebase",
      "Framer motion",
      "Stripe",
    ],
  },
  {
    id: 7,
    title: "Movielux",
    description: `MovieLux is a modern movie discovery web application built with React and TypeScript. It leverages the TMDB (The Movie Database) API to provide up-to-date movie information, and uses Redux Toolkit Query (RTK Query) for efficient and optimized data fetching and state management.`,
    projectLink: "https://movielux.vercel.app/",
    githubLink: "https://github.com/Royal-design/movielux",
    imageLink: "/movielux.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "RTK Query",
      "TMDB API",
    ],
  },
  {
    id: 2,
    title: "Home of Design Furniture",
    description: `Home of Design Furniture is a sleek and modern online furniture store that offers a seamless shopping experience across all devices. Customers can browse products, read reviews, manage their cart, and securely complete dummy purchases.`,
    projectLink: "https://home-of-design.vercel.app/",
    githubLink: "https://github.com/Royal-design/home-of-design",
    imageLink: "/hod.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Zod",
      "React Hook Form",
      "Firebase",
      "Framer motion",
      "Stripe",
    ],
  },
  {
    id: 3,
    title: "Ninja.Translator – AI Text Assistant",
    description: `Ninja.Translator is a smart, intuitive AI interface designed to streamline multilingual communication. Built with a sleek chat-style UI, it allows users to translate text into different languages and summarize lengthy content with ease, it is powered by Gemini AI models.`,
    projectLink: "https://codeninja-ai.vercel.app/",
    githubLink: "https://github.com/Royal-design/ninja-ai",
    imageLink: "/ninja.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Framer motion",
      "Gemini models",
    ],
  },
  {
    id: 4,
    title: "ChattyBee AI — Chat Assistant",
    description: `ChattyBee AI is a smart, web-based chat assistant that generates context-aware responses based on user input. Its primary focus is to simulate natural, human-like conversations with AI in a smooth and engaging interface.`,
    projectLink: "https://chatty-bee-ai.vercel.app/",
    githubLink: "https://github.com/Royal-design/chatty-bee-ai",
    imageLink: "/chattybee.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Firebase",
      "Gemini models",
    ],
  },
  {
    id: 5,
    title: "BeepME – Real-Time Chat App",
    description: `BeepME is a real-time chat application built with React and Firebase, designed to offer a fast, seamless, and modern messaging experience. It features secure user authentication (email/password and Google login), real-time messaging powered by Firebase`,
    projectLink: "https://beep-me.vercel.app/",
    githubLink: "https://github.com/Royal-design/BeepME",
    imageLink: "/beepme.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Firebase",
    ],
  },
  {
    id: 6,
    title: "Corex Metaverse: The Virtual Revolution",
    description: `Corex Metaverse is a futuristic event website built to simulate the experience of a virtual tech expo. It features a sleek neon-themed UI and an intuitive multi-step ticket generation system. Users can choose their ticket type, fill in personal details, and generate a personalized digital ticket, all with smooth form validation and persistent state handling`,
    projectLink: "https://metaverse-corex-event.vercel.app/",
    githubLink: "https://github.com/Royal-design/metaverse-event",
    imageLink: "/metaverse.webp",
    techStacks: [
      "React",
      "TypeScript",
      "Redux",
      "Tailwind",
      "ShadCN",
      "Firebase",
    ],
  },
];

export const otherProjects = [
  {
    id: 1,
    title: "Taskify",
    description: `Taskify is a clean, responsive task manager that lets users create, edit, and delete daily goals with ease.`,
    projectLink: "https://task-manager-ecru-pi-75.vercel.app/",
    githubLink: "https://github.com/Royal-design/task-manager",
    imageLink: "/taskify.webp",
    techStacks: ["React", "TypeScript", "ShadCN", "Firebase"],
  },
  {
    id: 2,
    title: "Clothing Store",
    description: `SimpleCloth is a basic clothing store app built with React & TypeScript, featuring a clean layout, cart functionality, and responsive design.`,
    projectLink: "https://clothing-store-jade.vercel.app/",
    githubLink: "https://github.com/Royal-design/shopping-cart",
    imageLink: "/clothestore.webp",
    techStacks: ["React", "TypeScript", "SCSS"],
  },
  {
    id: 3,
    title: "CGPA Calculator",
    description: `A responsive CGPA calculator built with React, TypeScript & Chakra UI. Easily compute your GPA by entering course units and grades.`,
    projectLink: "https://cgpa-calculator-one-wheat.vercel.app/",
    githubLink: "https://github.com/Royal-design/cgpacalculator",
    imageLink: "/cgpa.webp",
    techStacks: ["React", "TypeScript", "Chakra UI"],
  },
  {
    id: 4,
    title: "Basic Calculator",
    description: `A basic calculator built with HTML, CSS & JavaScript for simple arithmetic operations.`,
    projectLink: "https://calculator-eight-beta-25.vercel.app/",
    githubLink: "https://github.com/Royal-design/codsoft_3",
    imageLink: "/basic.webp",
    techStacks: ["HTML", "CSS", "JavaScript"],
  },
];
